/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

int *
add_1_svc(intpair *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("Calling add function\n");
	printf("Parameters: %d, %d\n", argp->a, argp->b);
	
	if(argp->ch==1)
		result = argp->a + argp->b; 	
	if(argp->ch==2)
		result = argp->a - argp->b; 
	if(argp->ch==3)
		result = argp->a * argp->b; 	
	if(argp->ch==4)
		result = argp->a / argp->b; 
	printf("Returning: %d\n", result);
	return &result;
}
