/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "reverse.h"

arg *revfunc_1_svc(arg *argp, struct svc_req *rqstp)
{
	static arg  result;
	int i,j,n;
	char t;
	char s[40],s1[40];

	strcpy(s,argp->str);
	strcpy(s1,s);
	printf("\n\nString received from client is : %s",s);
	
	n = strlen(s);
	
	for(i=0,j=n-1;i<n/2;i++,j--)
	{
		t = s[i];
		s[i] = s[j];
		s[j] = t;
	}

	strcpy(result.str,s);

	printf("\nString reversed and sent to client is : %s\n",result.str);
	if(strcmp(s,s1)==0)
		printf("Palindrome\n");
	fflush(stdout);
		
	return &result;
}
