/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "reverse.h"
#include<string.h>

void reverse_1(char *host, char *str)
{
	CLIENT *clnt;
	arg  *result;
	arg  revfuncarg;

	strcpy(revfuncarg.str,str);

#ifndef	DEBUG
	clnt = clnt_create (host, REVERSE, REVVER, "udp");

	if (clnt == NULL) 
	{
		clnt_pcreateerror (host);
		exit (1);
	}

#endif	/* DEBUG */

	result = revfunc_1(&revfuncarg, clnt);

	if (result == (arg *) NULL) 
	{
		clnt_perror (clnt, "call failed");
	}

	else
	printf("\nReversed String is : %s\n\n",result->str);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char str[40];
	
	if (argc < 3) {
		printf ("usage: %s server_host string\n", argv[0]);
		exit (1);
	}
	
	host = argv[1];
	
	strcpy(str,argv[2]);
	
	reverse_1 (host,str);

	exit (0);
}
